# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SX_YMXK_A' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SX_YMXK_A
pod 'AFNetworking', '~> 3.1.0'
pod 'Masonry', '~> 1.0.2'
pod 'SDWebImage', '~> 3.8.2'
pod 'MJRefresh', '~> 3.1.12'
end
